### ISSUE TITLE
Create audio file 

### ISSUE THREAD

**Issue by 5y** [KentCrawford/yatts#1]
Hi,
I can't find a manual about create audio output in python project(not Shell), how to do that ?

**Comment by KentCrawford** [comment]
Hey there.  Your comment made me realize I should probably add a helper function to do just this!  In the meantime, however, something like this would work.

    from yatts.google import TTS
    tts = TTS(text='Hello, world.', language='en', translate_to='fr')
    with open('test.mp3', 'wb') as fout:
        for segment in tts:
            fout.write(segment.audio)

I will work on adding a function to yatts to make this easier to do.  I'll post back here once it's implemented.

**Comment by 5y** [comment]
Thank you , it seems great.
I have another problem, In supported languages list they are exist a lot of language included Persian(fa) but when i try use fa replace fr in script the mp3 is empty whats your comment about that ?

**Comment by KentCrawford** [comment]
Well, that's a shame.  It seems Google is able to convert text into Persian, but is not able to then convert that text to speach.  https://translate.google.com/#en/fa/test .  A speaker icon would show up in the Persian side if it could.  Notice the speaker icon here?  https://translate.google.com/#en/de/test

I am very sorry about that!  I didn't realize the audio wouldn't work for some languages.  I'll be sure to update the supported languages list.  Thank you for brining this to my attention.

**Comment by 5y** [comment]
Sure It's OK. :+1: 
I just a little bit Googling about that and "Yes" Unfortunately Google not able to convert text to speech specific in Persian, but it available in Android Google Text to speech application !! :D

**Comment by KentCrawford** [comment]
Interesting!  I'll have to look in to how Android Google Text to Speech is able to do it and see if it's something I can implement in yatts.  Thanks for the info!

**Comment by KentCrawford** [comment]
I've added a save method to yatts.google.TTS to make it easier to save the .mp3 to file.  It's available in version 0.2.2 found here:  https://pypi.python.org/pypi/yatts

    from yatts.google import TTS
    tts = TTS(text='Hello, world.', language='en', translate_to='fr')
    tts.save('hello_world.mp3')

I also updated the supported languages list.

Hopefully yatts will be able to support Persian one day soon!

**Comment by 5y** [comment]
Dear Kent ,
Thank you , if you need any help about Persian feature in yatts don't
hesitate to ask me.

Bests,
Rehb
